export const shopCategories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "home-kitchen", label: "Home & Kitchen" },
  { value: "health-beauty", label: "Health & Beauty" },
  { value: "sports-outdoors", label: "Sports & Outdoors" },
  { value: "kids-baby", label: "Kids & Baby" },
  { value: "automotive", label: "Automotive" },
  { value: "books-media", label: "Books, Music & Movies" },
  { value: "food-beverages", label: "Groceries & Food" },
  { value: "furniture", label: "Furniture & Decor" },
  { value: "tools-diy", label: "Tools & DIY" },
  { value: "hobbies", label: "Hobbies & Collectibles" },
  { value: "pets", label: "Pet Supplies" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "digital", label: "Digital Goods & Software" },
  { value: "garden", label: "Garden & Outdoor Living" },
  { value: "appliances", label: "Home Appliances" },
  { value: "art", label: "Art, Crafts & Sewing" },
  { value: "office", label: "Office & School Supplies" },
  { value: "travel", label: "Travel & Luggage" },
];