name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize line endings
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'

      - name: Clean dependencies
        run: rm -rf node_modules && rm -rf ~/.npm && rm -rf ~/.nx

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint, Test, and Build
        run: npx nx run-many -t lint test build

      - name: Auto-fix CI suggestions (Nx)
        if: always()
        run: npx nx fix-ci
